const cache_name = "game-v1";
const assets = [
    "/",
    "/ABC.png",
    "/AandB.png",
    "/first_click.gif",
    "/game.html",
    "/grid6*8.png",
    "/icons",
    "/index.html",
    "/isocolumn.gif",
    "/isocolumn.png",
    "/isorow.gif",
    "/isorow.png",
    "/manifest.json",
    "/script.js",
    "/script_instruction.js",
    "/second_click.gif",
    "/set_grid.png",
    "/show-instruction.gif",
    "/style_instruction.css",
    "/styles.css",
    "/third_click.gif",
    `   "/icons/Square150x150Logo.scale-100.png",
    "/icons/Square150x150Logo.scale-125.png",
    "/icons/Square150x150Logo.scale-150.png",
    "/icons/Square150x150Logo.scale-200.png",
    "/icons/Square150x150Logo.scale-400.png",
    "/icons/Square310x310Logo.scale-100.png",
    "/icons/Square310x310Logo.scale-125.png",
    "/icons/Square310x310Logo.scale-150.png",
    "/icons/Square310x310Logo.scale-200.png",
    "/icons/Square310x310Logo.scale-400.png",
    "/icons/Square44x44Logo.scale-100.png",
    "/icons/Square44x44Logo.scale-125.png",
    "/icons/Square44x44Logo.scale-150.png",
    "/icons/Square44x44Logo.scale-200.png",
    "/icons/Square44x44Logo.scale-400.png",
    "/icons/Square44x44Logo.targetsize-16.png",
    "/icons/Square44x44Logo.targetsize-16_altform-unplated.png",
    "/icons/Square44x44Logo.targetsize-24.png",
    "/icons/Square44x44Logo.targetsize-24_altform-unplated.png",
    "/icons/Square44x44Logo.targetsize-256.png",
    "/icons/Square44x44Logo.targetsize-256_altform-unplated.png",
    "/icons/Square44x44Logo.targetsize-32.png",
    "/icons/Square44x44Logo.targetsize-32_altform-unplated.png",
    "/icons/Square44x44Logo.targetsize-48.png",
    "/icons/Square44x44Logo.targetsize-48_altform-unplated.png",
    "/icons/Square71x71Logo.scale-100.png",
    "/icons/Square71x71Logo.scale-125.png",
    "/icons/Square71x71Logo.scale-150.png",
    "/icons/Square71x71Logo.scale-200.png",
    "/icons/Square71x71Logo.scale-400.png",
    "/icons/StoreLogo.png",
    "/icons/StoreLogo.scale-100.png",
    "/icons/StoreLogo.scale-125.png",
    "/icons/StoreLogo.scale-150.png",
    "/icons/StoreLogo.scale-200.png",
    "/icons/StoreLogo.scale-400.png",
    "/icons/android-launchericon-144-144.png",
    "/icons/android-launchericon-192-192.png",
    "/icons/android-launchericon-48-48.png",
    "/icons/android-launchericon-512-512.png",
    "/icons/android-launchericon-72-72.png",
    "/icons/android-launchericon-96-96.png",
    "/icons/chrome-extensionmanagementpage-48-48.png",
    "/icons/chrome-favicon-16-16.png",
    "/icons/chrome-installprocess-128-128.png",
    "/icons/firefox-general-128-128.png",
    "/icons/firefox-general-16-16.png",
    "/icons/firefox-general-256-256.png",
    "/icons/firefox-general-32-32.png",
    "/icons/firefox-general-48-48.png",
    "/icons/firefox-general-64-64.png",
    "/icons/firefox-general-90-90.png",
    "/icons/firefox-marketplace-128-128.png",
    "/icons/firefox-marketplace-512-512.png",
    "/icons/msteams-192-192.png",
    "/icons/msteams-silhouette-32-32.png",
    "/icons/windows-smallsquare-24-24.png",
    "/icons/windows-smallsquare-30-30.png",
    "/icons/windows-smallsquare-42-42.png",
    "/icons/windows-smallsquare-54-54.png",
    "/icons/windows-squarelogo-120-120.png",
    "/icons/windows-squarelogo-150-150.png",
    "/icons/windows-squarelogo-210-210.png",
    "/icons/windows-squarelogo-270-270.png",
    "/icons/windows-storelogo-50-50.png",
    "/icons/windows-storelogo-70-70.png",
    "/icons/windows-storelogo-90-90.png",
    "/icons/windowsphone-appicon-106-106.png",
    "/icons/windowsphone-appicon-44-44.png",
    "/icons/windowsphone-appicon-62-62.png",
    "/icons/windowsphone-mediumtile-150-150.png",
    "/icons/windowsphone-mediumtile-210-210.png",
    "/icons/windowsphone-mediumtile-360-360.png",
    "/icons/windowsphone-smalltile-170-170.png",
    "/icons/windowsphone-smalltile-71-71.png",
    "/icons/windowsphone-smalltile-99-99.png",
    "/icons/windowsphone-storelogo-120-120.png",
    "/icons/windowsphone-storelogo-50-50.png",
    "/icons/windowsphone-storelogo-70-70.png",`
]
self.addEventListener("install", installEvent => {
    installEvent.waitUntil(
        caches.open(cache_name).then(cache => {
            cache.add("/")
            cache.add("/ABC.png")
            cache.add("/first_click.gif")
            cache.add("/game.html")
            cache.add("/grid6*8.png")
            cache.add("/icons")
            cache.add("/index.html")
            cache.add("/isocolumn.gif")

        })
    )
})
self.addEventListener("fetch", fetchEvent => {
    fetchEvent.respondWith(
        caches.match(fetchEvent.request).then(res => {
            console.log("fetch request");
            console.log(fetchEvent.request);
            console.log("caches.match result");
            console.log(res)
            return res || fetch(fetchEvent.request)
        })
    )
})